version: '3.8'

services:

  redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - "6379:6379"

  web-client:
    build: . # Собираем образ из Dockerfile
    ports:
      - "3000:3000" # Пробрасываем порт Web Client
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379 # Подключаемся к Redis

  mock-server:
    image: node:16 # Используем официальный образ Node.js
    working_dir: /app
    volumes:
      - .:/app # Монтируем текущую папку в контейнер
    command: node mockServer.js # Запускаем заглушку
    ports:
      - "5000:5000" # Пробрасываем порт заглушки
    depends_on:
      - redis